name: Build release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Build distribution
        run: |
          python -m pip install --upgrade pip wheel
          pip install "setuptools<70" build
          python -m build
